name: gtavc_builder
description: "OpenStreetMap to GTA Vice City binary assets converter (.dff, .txd, .col)"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  path_provider: ^2.1.2
  ffi: ^2.1.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
