#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <cstring>
#include <algorithm>
#include "osm_parser.h"

#if defined(__ANDROID__)
#include <android/log.h>
#define LOG_TAG "GTAVC_ENGINE"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)
#else
#define LOGI(...) printf(__VA_ARGS__)
#define LOGE(...) fprintf(stderr, __VA_ARGS__)
#endif

bool ExportChunkDff(const MapChunk& chunk, const std::string& outPath, int platform);
bool ExportChunkCol(const MapChunk& chunk, const std::string& outPath);
bool ExportSharedTxd(const std::string& outPath, int platform);

static constexpr size_t SECTOR_SIZE = 2048;

#pragma pack(push, 1)
struct DirEntry {
    uint32_t offset;  // Секторно отместване
    uint32_t size;    // Размер в сектори
    char name[24];    // Име на файла
};
#pragma pack(pop)

static bool ExportIdeFile(const std::vector<MapChunk>& chunks, const std::string& outPath) {
    std::ofstream out(outPath);
    if (!out.is_open()) return false;

    out << "# Generated by GTA VC Map Builder (OSM)\n";
    out << "objs\n";
    int startId = 18000;
    for (size_t i = 0; i < chunks.size(); ++i) {
        out << (startId + i) << ", " << chunks[i].chunkName << ", osm_world, 1, 650, 0\n";
    }
    out << "end\n";
    out << "txdp\nend\n2dfx\nend\n";
    out.close();
    return true;
}

static bool ExportIplFile(const std::vector<MapChunk>& chunks, const std::string& outPath) {
    std::ofstream out(outPath);
    if (!out.is_open()) return false;

    out << "# Generated by GTA VC Map Builder (OSM)\n";
    out << "inst\n";
    int startId = 18000;
    for (size_t i = 0; i < chunks.size(); ++i) {
        out << (startId + i) << ", " << chunks[i].chunkName << ", 0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0\n";
    }
    out << "end\n";
    out << "cull\nend\npath\nend\n";
    out.close();
    return true;
}

static bool PackImgArchive(const std::vector<std::string>& filePaths, const std::string& outImgPath, const std::string& outDirPath) {
    std::ofstream imgFile(outImgPath, std::ios::out | std::ios::binary);
    std::ofstream dirFile(outDirPath, std::ios::out | std::ios::binary);

    if (!imgFile.is_open() || !dirFile.is_open()) return false;

    uint32_t currentSector = 0;

    for (const auto& path : filePaths) {
        std::ifstream src(path, std::ios::in | std::ios::binary | std::ios::ate);
        if (!src.is_open()) continue;

        size_t fileSize = src.tellg();
        src.seekg(0, std::ios::beg);

        std::vector<char> buffer(fileSize);
        src.read(buffer.data(), fileSize);
        src.close();

        // Изчисляване на името на файла
        size_t lastSlash = path.find_last_of("/\\");
        std::string fileName = (lastSlash == std::string::npos) ? path : path.substr(lastSlash + 1);

        uint32_t sectorCount = static_cast<uint32_t>((fileSize + SECTOR_SIZE - 1) / SECTOR_SIZE);

        DirEntry entry;
        std::memset(&entry, 0, sizeof(DirEntry));
        entry.offset = currentSector;
        entry.size = sectorCount;
        std::strncpy(entry.name, fileName.c_str(), 23);

        dirFile.write(reinterpret_cast<const char*>(&entry), sizeof(DirEntry));

        imgFile.write(buffer.data(), fileSize);

        // Подравняване до 2048 байта с нули
        size_t padBytes = (sectorCount * SECTOR_SIZE) - fileSize;
        if (padBytes > 0) {
            std::vector<char> padding(padBytes, 0);
            imgFile.write(padding.data(), padBytes);
        }

        currentSector += sectorCount;
    }

    imgFile.close();
    dirFile.close();
    return true;
}

static bool MergeColFiles(const std::vector<std::string>& colPaths, const std::string& mergedPath) {
    std::ofstream out(mergedPath, std::ios::out | std::ios::binary);
    if (!out.is_open()) return false;

    for (const auto& path : colPaths) {
        std::ifstream src(path, std::ios::in | std::ios::binary);
        if (src.is_open()) {
            out << src.rdbuf();
            src.close();
        }
    }
    out.close();
    return true;
}

static bool ExportInstallGuide(const std::vector<MapChunk>& chunks, const std::string& outPath) {
    std::ofstream out(outPath);
    if (!out.is_open()) return false;

    out << "=================================================================\n";
    out << "   GTA VICE CITY - ИНСТРУКЦИИ ЗА ИНСТАЛИРАНЕ НА КАРТАТА         \n";
    out << "=================================================================\n\n";
    out << "Общо генерирани 3D квартали: " << chunks.size() << "\n\n";
    out << "1. СТЪПКА: Копирайте всички файлове от тази папка в:\n";
    out << "   GTA Vice City/data/maps/osm/\n\n";
    out << "2. СТЪПКА: Отворете файла GTA Vice City/data/gta_vc.dat с текстов редактор\n";
    out << "   и добавете следните 4 реда в секциите за карти:\n\n";
    out << "   CDIMAGE DATA\\MAPS\\OSM\\OSM_MAP.IMG\n";
    out << "   IDE DATA\\MAPS\\OSM\\OSM_WORLD.IDE\n";
    out << "   IPL DATA\\MAPS\\OSM\\OSM_WORLD.IPL\n";
    out << "   COLFILE 0 DATA\\MAPS\\OSM\\OSM_WORLD.COL\n\n";
    out << "3. СТЪПКА: СТАРТИРАЙТЕ ИГРАТА!\n";
    out << "   Картата ще се зареди автоматично.\n";
    out << "   Координати на центъра на града: X: 0.0, Y: 0.0, Z: 15.0\n";
    out << "=================================================================\n";
    out.close();
    return true;
}

extern "C" {

#if defined(_WIN32)
__declspec(dllexport)
#else
__attribute__((visibility("default")))
#endif
int ProcessOsmData(const char* osmPath, const char* outDir, int targetPlatform, void (*progressCb)(float)) {
    if (!osmPath || !outDir) {
        LOGE("Невалидни входни параметри за ProcessOsmData");
        return -1;
    }

    std::string osmFilePath(osmPath);
    std::string outputDirectory(outDir);

    LOGI("Започва обработка на OSM файл: %s", osmFilePath.c_str());
    if (progressCb) progressCb(0.05f);

    OsmParser parser;
    bool parseSuccess = parser.ParseStream(osmFilePath, [&](float p) {
        if (progressCb) progressCb(p);
    });

    if (!parseSuccess) {
        LOGE("Грешка при парсване на OSM XML файла!");
        return -2;
    }

    const auto& chunks = parser.GetChunks();
    LOGI("Успешно генерирани %zu порции (chunks)", chunks.size());

    // 1. Генериране на общ TXD файл
    std::string txdPath = outputDirectory + "/osm_world.txd";
    ExportSharedTxd(txdPath, targetPlatform);

    // 2. Генериране на .IDE, .IPL и Инсталационен гайд
    ExportIdeFile(chunks, outputDirectory + "/osm_world.ide");
    ExportIplFile(chunks, outputDirectory + "/osm_world.ipl");
    ExportInstallGuide(chunks, outputDirectory + "/install_guide.txt");

    // 3. Генериране на .DFF и .COL за всеки Chunk
    std::vector<std::string> dffFiles;
    std::vector<std::string> colFiles;
    dffFiles.push_back(txdPath);

    float startProgress = 0.55f;
    float step = 0.30f / static_cast<float>(std::max<size_t>(1, chunks.size()));

    for (size_t i = 0; i < chunks.size(); ++i) {
        const auto& chunk = chunks[i];
        std::string dffPath = outputDirectory + "/" + chunk.chunkName + ".dff";
        std::string colPath = outputDirectory + "/" + chunk.chunkName + ".col";

        ExportChunkDff(chunk, dffPath, targetPlatform);
        ExportChunkCol(chunk, colPath);

        dffFiles.push_back(dffPath);
        colFiles.push_back(colPath);

        if (progressCb) {
            progressCb(startProgress + static_cast<float>(i + 1) * step);
        }
    }

    // 4. Пакетиране на собствен GTA .IMG / .DIR архив
    std::string imgPath = outputDirectory + "/osm_map.img";
    std::string dirPath = outputDirectory + "/osm_map.dir";
    PackImgArchive(dffFiles, imgPath, dirPath);

    // 5. Обединяване на всички колизии в един osm_world.col
    std::string mergedColPath = outputDirectory + "/osm_world.col";
    MergeColFiles(colFiles, mergedColPath);

    LOGI("Всички GTA Vice City активи са напълно готови!");
    if (progressCb) progressCb(1.0f);

    return 0;
}

}
