#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <algorithm>
#include "osm_parser.h"

#if defined(__ANDROID__)
#include <android/log.h>
#define LOG_TAG "GTAVC_ENGINE"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)
#else
#define LOGI(...) printf(__VA_ARGS__)
#define LOGE(...) fprintf(stderr, __VA_ARGS__)
#endif

bool ExportChunkDff(const MapChunk& chunk, const std::string& outPath, int platform);
bool ExportChunkCol(const MapChunk& chunk, const std::string& outPath);
bool ExportSharedTxd(const std::string& outPath, int platform);

static bool ExportIdeFile(const std::vector<MapChunk>& chunks, const std::string& outPath) {
    std::ofstream out(outPath);
    if (!out.is_open()) return false;

    out << "# Generated by GTA VC Map Builder (OSM)\n";
    out << "objs\n";
    int startId = 18000;
    for (size_t i = 0; i < chunks.size(); ++i) {
        // ID, ModelName, TxdName, MeshCount, DrawDistance, Flags
        out << (startId + i) << ", " << chunks[i].chunkName << ", osm_world, 1, 650, 0\n";
    }
    out << "end\n";
    out << "txdp\nend\n2dfx\nend\n";
    out.close();
    return true;
}

static bool ExportIplFile(const std::vector<MapChunk>& chunks, const std::string& outPath) {
    std::ofstream out(outPath);
    if (!out.is_open()) return false;

    out << "# Generated by GTA VC Map Builder (OSM)\n";
    out << "inst\n";
    int startId = 18000;
    for (size_t i = 0; i < chunks.size(); ++i) {
        // ID, ModelName, Interior, PosX, PosY, PosZ, ScaleX, ScaleY, ScaleZ, RotX, RotY, RotZ, RotW
        out << (startId + i) << ", " << chunks[i].chunkName << ", 0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0\n";
    }
    out << "end\n";
    out << "cull\nend\npath\nend\n";
    out.close();
    return true;
}

static bool ExportInstallGuide(const std::vector<MapChunk>& chunks, const std::string& outPath) {
    std::ofstream out(outPath);
    if (!out.is_open()) return false;

    out << "=========================================================\n";
    out << "   GTA VICE CITY - ИНСТРУКЦИИ ЗА ИНСТАЛИРАНЕ НА КАРТАТА   \n";
    out << "=========================================================\n\n";
    out << "Общо генерирани 3D квартали (chunks): " << chunks.size() << "\n\n";
    out << "1. ИНСТАЛАЦИЯ В GTA VICE CITY (PC / Android):\n";
    out << "--------------------------------------------\n";
    out << "А) Поставете файловете osm_world.ide и osm_world.ipl в:\n";
    out << "   GTA Vice City/data/maps/osm/\n\n";
    out << "Б) Импортирайте всички .dff файлове и osm_world.txd в:\n";
    out << "   GTA Vice City/models/gta3.img (чрез IMG Tool или Fastman92 Limit Adjuster)\n\n";
    out << "В) Добавете следните редове във файла data/gta_vc.dat:\n";
    out << "   IDE DATA\\MAPS\\OSM\\OSM_WORLD.IDE\n";
    out << "   IPL DATA\\MAPS\\OSM\\OSM_WORLD.IPL\n\n";
    out << "2. ТЕЛЕПОРТИРАНЕ В ИГРАТА:\n";
    out << "   Координати на новия град: X: 0.0, Y: 0.0, Z: 15.0\n";
    out << "=========================================================\n";
    out.close();
    return true;
}

extern "C" {

#if defined(_WIN32)
__declspec(dllexport)
#else
__attribute__((visibility("default")))
#endif
int ProcessOsmData(const char* osmPath, const char* outDir, int targetPlatform, void (*progressCb)(float)) {
    if (!osmPath || !outDir) {
        LOGE("Невалидни входни параметри за ProcessOsmData");
        return -1;
    }

    std::string osmFilePath(osmPath);
    std::string outputDirectory(outDir);

    LOGI("Започва обработка на OSM файл: %s", osmFilePath.c_str());
    if (progressCb) progressCb(0.05f);

    OsmParser parser;
    bool parseSuccess = parser.ParseStream(osmFilePath, [&](float p) {
        if (progressCb) progressCb(p);
    });

    if (!parseSuccess) {
        LOGE("Грешка при парсване на OSM XML файла!");
        return -2;
    }

    const auto& chunks = parser.GetChunks();
    LOGI("Успешно генерирани %zu порции (chunks)", chunks.size());

    // 1. Генериране на общ TXD (Texture Dictionary) файл
    std::string txdPath = outputDirectory + "/osm_world.txd";
    if (!ExportSharedTxd(txdPath, targetPlatform)) {
        LOGE("Грешка при експортиране на TXD файл");
        return -3;
    }

    // 2. Генериране на .IDE и .IPL файлове за разполагане в играта
    ExportIdeFile(chunks, outputDirectory + "/osm_world.ide");
    ExportIplFile(chunks, outputDirectory + "/osm_world.ipl");
    ExportInstallGuide(chunks, outputDirectory + "/install_guide.txt");

    // 3. Генериране на .DFF и .COL за всеки Chunk
    float startProgress = 0.55f;
    float step = 0.45f / static_cast<float>(std::max<size_t>(1, chunks.size()));

    for (size_t i = 0; i < chunks.size(); ++i) {
        const auto& chunk = chunks[i];
        std::string dffPath = outputDirectory + "/" + chunk.chunkName + ".dff";
        std::string colPath = outputDirectory + "/" + chunk.chunkName + ".col";

        ExportChunkDff(chunk, dffPath, targetPlatform);
        ExportChunkCol(chunk, colPath);

        if (progressCb) {
            progressCb(startProgress + static_cast<float>(i + 1) * step);
        }
    }

    LOGI("Всички GTA Vice City файлове (.dff, .txd, .col, .ide, .ipl) са генерирани успешно!");
    if (progressCb) progressCb(1.0f);

    return 0;
}

}
